version: "3.9"

services:
  api:
    image: ghcr.io/ka7eh/ctsm-api:${API_VERSION:-latest}
    restart: unless-stopped
    entrypoint: /ctsm-api/docker/entrypoint_api.sh
    environment:
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
    networks:
      - default
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ./docker/entrypoint_api.sh:/ctsm-api/docker/entrypoint_api.sh
      - ./docker/.env:/ctsm-api/.env
      - ./resources:/ctsm-api/resources

  tasks:
    image: ghcr.io/ka7eh/ctsm-api:${API_VERSION:-latest}
    restart: unless-stopped
    entrypoint: /ctsm-api/docker/entrypoint_tasks.sh
    environment:
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
    networks:
      - default
    volumes:
      - ./docker/.env:/ctsm-api/.env
      - ./resources:/ctsm-api/resources

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - default
  
  ui:
    image: ghcr.io/ka7eh/fates-platform:${PLATFORM_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ${PORT:-8080}:80

networks:
  default:
